services:
  mongo:
    image: mongo:8.0.12-rc0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    #volumes:
    #  - ./local_only/mongo_db:/data/db  # persist MongoDB data locally
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"  # access UI at http://localhost:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
